apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: custom
spec:

  replicas: 3
  image: postgres:16.2
  port: 5432

  #imagePullSecrets:
  #  - name: my-private-docker-repo-secret

  database:
    size: 200Mi
    #storageClassName: standard
    #volumeMount: /var/lib/postgres/data

  customConfig: mypostgres-conf

  #failover:
  #  isDisabled: true
  #  promotePod: "mypostgres-3-0"

  #backup:
  #  schedule: "*/1 * * * *"
  #  pvcName: backup
  #  volumeMount: /tmp/mypostgres

  #containerSecurityContext:
  #  allowPrivilegeEscalation: false
  #  capabilities:
  #    drop:
  #      - ALL
  #  seccompProfile:
  #    type: RuntimeDefault
  #  runAsNonRoot: true
  #  readOnlyRootFilesystem: false
  #  privileged: false

  #securityContext:
  #  runAsUser: 1001
  #  runAsGroup: 1001
  #  fsGroup: 1001
  #  runAsNonRoot: true

  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mypostgres-secret
          key: superUserPassword

    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mypostgres-secret
          key: replicationUserPassword

    - name: POSTGRES_MYAPP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mypostgres-secret
          key: myAppUserPassword
